- cookbook/fgcmMakeLutHscFromTable.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmMakeLut.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Add support for latest fgcm, including fitting in ln(PWV) space, quadratic
temporal variation of ln(PWV), offsets between cross-calibrated filters (e.g.,
HSC r/r2 and i/i2), and estimation of the systematic error floor in the
calibration. Another fit cycle was added to the tests, as this excercises
key bits of the code where fit parameters are re-ingested.
> DM-16700: Update for latest version of fgcm, including log PWV and filter offsets.

- python/lsst/fgcmcal/fgcmOutputProducts.py
- tests/test_fgcmcal_hsc.py
The PhotoCal task expects instFlux inputs, and we now explicitly pass instFlux
values rather than Jansky fluxes.  This fix means that the computed zeropoint
offsets are appropriately approximately 0 rather than approximately 9.
> DM-16871: Change flux to be calibrated from 'flux' to 'instFlux'.

- cookbook/fgcmFitCycleHscCookbook_cycle00_config.py
- python/lsst/fgcmcal/fgcmBuildStars.py
- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/utilities.py
- tests/test_ccdoffsets.py
- tests/test_fgcmcal_hsc.py
This update deprecates the pixelScale configuration parameter which is no
longer necessary now that all the camera units are correct and makeSkyWcs works
properly for HSC.  However, due to a bug in the data files in
testdata_jointcal, there is still an HSC-specific hack that can be fixed after
DM-17597 is complete.
> DM-16490: Update computeCcdOffsets() to use makeSkyWcs

- cookbook/README.md
- cookbook/fgcmFitCycleHscCookbook_cycle00_config.py
- python/lsst/fgcmcal/fgcmBuildStars.py
- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Add the ability to use externally calibrated aperture corrections for use in tract mode when there isn't sufficient data to fit them empirically.  Also fix a dataRef logic error when running globally (e.g. PDR1) and the ability to output stars in tract mode, used for qa and debugging.
> DM-21501: Implement internal aperture corrections for fgcmcal tract mode

- python/lsst/fgcmcal/fgcmOutputProducts.py
- tests/fgcmcalTestBase.py
Ambiguities in how different version of numpy handled the implicit conversions
seemed to create problems in the round-trip mag-flux conversion tests.  By
being explicit with float64s in all cases this problem should go away.
> DM-21982: Update mag-flux conversions to explicitly use float64

- cookbook/fgcmFitCycleHscCookbook_cycle00_config.py
- python/lsst/fgcmcal/fgcmBuildStars.py
- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Now fgcm will aggregate the stars that have the calib_psfCandidate flag and
count the number of times this is set (as well as the total number of
observations).  The output is in the final output refcat with the
band_nPsfCandidate field.
> DM-21814: Add tracking of calib_psfCandidate flags.

- python/lsst/fgcmcal/fgcmBuildStars.py
- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Use new features of afw, including `PixelAreaBoundedField` and `ProductBoundedField` to decompose photometric calibration into wcs jacobian component, star-flat (illumination correction) component, and gray component.
> DM-20163: Use PixelAreaBoundedField in fgcmcal calibration outputs

- cookbook/README.md
- cookbook/fgcmBuildStarsHsc.py
- python/lsst/fgcmcal/fgcmBuildStars.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Also update code to remove alternate ways of calling the code that were unused
except in the tests.  The tests have been updated accordingly.
> DM-22798: Update fgcmcal cookbook on proper usage of checkAllCcds config.

- python/lsst/fgcmcal/fgcmBuildStars.py
- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmMakeLut.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- setup.cfg
- tests/config/fgcmBuildStarsHsc.py
- tests/config/fgcmCalibrateTractHsc.py
- tests/config/fgcmFitCycleHsc.py
- tests/config/fgcmMakeLutHsc.py
- tests/config/fgcmOutputProductsHsc.py
- tests/config/sdssColortermsHsc.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Update tests accordingly, and also update FGCM code to elegantly handle missing bands.
> DM-23331: Add support for default config files in obs_subaru

- cookbook/fgcmFitCycleHscCookbook_cycle00_config.py
- cookbook/fgcmMakeLutHscFromTable.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- tests/config/fgcmFitCycleHsc.py
- tests/fgcmcalTestBase.py
This PR includes a few changes required to get the PDR2 reprocessing through.
> DM-23526: Fix fgcmcal issues exposed during PDR2 run

- python/lsst/fgcmcal/utilities.py
Internally, these were reported by fgcm as 64-bit floats, and now they are
properly persisted by the butler as 64-bit floats.
> DM-23630: Persist all fgcm zeropoint values as float64

- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- tests/config/fgcmFitCycleHsc.py
- tests/test_fgcmcal_hsc.py
- tests/test_fitcycle.py
All list fields which depended on getting the band order correct have been
deprecated and replaced with dict mappings to avoid many possible index
errors.  This is supported with 3.2.0 version of fgcm.  Additional
FutureWarnings from numpy 1.17 have also been fixed.
> DM-23699: Update fgcmcal default config format

- python/lsst/fgcmcal/fgcmCalibrateTract.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
Also tighten test tolerances now that various platforms give consistent results at the <1e-6 level.
> DM-25114: Update internal fgcm math to always use 64-bit floats

- python/lsst/fgcmcal/fgcmBuildStars.py
- python/lsst/fgcmcal/fgcmBuildStarsBase.py
- python/lsst/fgcmcal/fgcmBuildStarsTable.py
- python/lsst/fgcmcal/fgcmCalibrateTractBase.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
The local background subtraction code has been refactored to move the
computations into the fgcm code.  This allows fgcm to compute background offset
statistics and account for any net offsets in the zeropoints.  The chromatic
correction code has been updated to report the average chromatic correction per
ccd.  This yields better repeatability when the full pipeline does not include
chromatic terms (as is the case currently).  Additional tests have been added
to check for remaining net offsets and ensure they are small (<2 mmag).
> DM-26085: Fix fgcmcal zeropoint offset due to background offset.

- python/lsst/fgcmcal/fgcmBuildStarsBase.py
- python/lsst/fgcmcal/fgcmBuildStarsTable.py
- python/lsst/fgcmcal/fgcmCalibrateTractBase.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/utilities.py
- tests/config/fgcmFitCycleHsc.py
This fixes two bugs.  The first is that the fgcm filterToBand expects no extra filters, so the full physicalFilterMap needs to be pruned.  The second is the background detector retrieval in gen3.
> DM-29299: Clean up physicalFilterMap and fix background retrieval

- python/lsst/fgcmcal/fgcmBuildStarsTable.py
Just having a dataref is insufficient in the case that a raw exists
but ISR processing failed.
> DM-29359: Add explicit check for calexp dataset existence in the repo.

- python/lsst/fgcmcal/fgcmCalibrateTractBase.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- python/lsst/fgcmcal/utilities.py
- tests/config/fgcmBuildStarsHsc.py
- tests/config/fgcmFitCycleHsc.py
- tests/fgcmcalTestBase.py
- tests/pipelines/fgcmFullPipelineHsc.yaml
- tests/test_fgcmcal_hsc.py
`FgcmFitCycleTask` has been updated to allow multiple fit cycles to be run at once.  This, in turn, allows the full fgcmcal (build stars; multiple fit cycles; output photoCalibs) to be run as a single pipeline.  The gen3 tests now share a common test repo.
> DM-29348: Add ability to run global fgcmcal in a single pipeline.

- tests/test_apertures.py
- tests/test_fgcmcal_hsc.py
- tests/test_fgcmcal_hsc_gen2.py
- tests/test_focalPlaneProjector.py
- tests/test_loadref_hsc.py
As part of creating the gen3 cfht testdata, I reorganized the hsc data; this makes fgcmcal work with it.
> DM-29535: Create gen3 cfht testdata_jointcal repos

- python/lsst/fgcmcal/fgcmBuildStarsBase.py
- python/lsst/fgcmcal/fgcmBuildStarsTable.py
- python/lsst/fgcmcal/fgcmCalibrateTractBase.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/focalPlaneProjector.py
- python/lsst/fgcmcal/utilities.py
- tests/config/fgcmFitCycleHsc.py
- tests/test_fgcmcal_hsc.py
- tests/test_fgcmcal_hsc_gen2.py
- tests/test_fitcycle.py
By default, only the per-star and global offsets are computed because of the extra computation time.  These values can also be easily computed in a post-processing step.
> DM-24738: Add background offset tracking to fgcmcal

- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/utilities.py
- tests/config/fgcmFitCycleHsc.py
- tests/test_fgcmcal_hsc.py
This PR adds support for the new fgcm 3.9.0 which includes...
1) Reference star color residuals to judge quality of color terms
2) Color cuts to apply specifically to reference stars
3) A per-visit offset based on reference stars that smooths out uniformity variations in surveys (such as HSC SSP) that are not ideally designed for self-calibration.  In particular, this helps with offsets caused by the fgcm model being tripped up by the large changes from HSC-R -> HSC-R2 and HSC-I -> HSC-I2 with limited overlap.
This PR does not change the default configuration or behavior of fgcmcal.
> DM-31880: Add support for new fgcm reference star options.

- ups/fgcmcal.cfg
This PR stops C++ imports of `utils`, fixing a missing tagfile error; `utils` is pure Python, and it's `cpputils` that could potentially produce Doxygen tagfiles.
> DM-12659: Clean up Doxygen tagfile imports

- tests/test_fgcmcal_hsc.py
fgcm is being updated to avoid the hexbin bug in matplotlib=3.6.0.  This involves not making an empty log-bin hexbin plot and thus the test for the produced plots needs to be modified.
> DM-36276: Update test because fgcm is no longer producing an empty plot.

- tests/test_fgcmcal_hsc.py
The values are now computed in fgcm using float64 internally, which removes some floating-point rounding errors.  The new values are "more correct" and also consistent across scipy versions.
> DM-36944: Update lookup table comparison values after changing to float64.

- python/lsst/fgcmcal/fgcmBuildFromIsolatedStars.py
This PR fixes a flag loading issue, and an index error that can come with very thin data like rc2_subset when all of the observations of a given star are flagged as bad due to having no flux after correcting for the local background.
> DM-38398: Fix crashes exposed by rc2_subset.

- tests/fgcmcalTestBase.py
- tests/test_loadref_hsc.py
> DM-38210: Use butler.get() rather than deprecated getDirect()

- python/lsst/fgcmcal/fgcmBuildStarsTable.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- tests/config/fgcmBuildStarsTableHsc.py
Note that the default now uses the isolated star input, which uses detect_isPrimary with https://github.com/lsst/pipe_tasks/pull/789
> DM-39141: Add doRequirePrimary to star selector when using tables directly.

- python/lsst/fgcmcal/fgcmBuildFromIsolatedStars.py
- python/lsst/fgcmcal/fgcmBuildStarsTable.py
- python/lsst/fgcmcal/fgcmCalibrateTractTable.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
This is part of a new, slightly-better fix for DM-40243.
> DM-40322: Implement new connections hook for refcat lookups.

- python/lsst/fgcmcal/fgcmBuildFromIsolatedStars.py
- python/lsst/fgcmcal/fgcmCalibrateTractBase.py
- python/lsst/fgcmcal/fgcmFitCycle.py
- python/lsst/fgcmcal/fgcmOutputProducts.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
This uses the new version of fgcm (PR https://github.com/lsst/fgcm/pull/39).  
This takes advantage of various optimizations and also a fix to https://github.com/esheldon/esutil/issues/87
Apparently this has been "loose" forever but it just happened to work okay until now.
Using this branch and numpy 1.24 the fgcmcal tests are 5% faster (and this is a lower limit on the speed improvement in larger dataset). Using this branch and numpy 1.26 the fgcmcal tests are another 5% faster still.
> DM-42285: Update for use with future numpy (1.25+) and tighten down loose ends.

- tests/fgcmcalTestBase.py
The 'root' argument never existed, but until DM-40441 this method seems to have accidentally accepted (and ignored) arbitrary kwargs.
> DM-40441: Drop unnecessary argument to SimplePipelineExecutor.from_pipeline.

- python/lsst/fgcmcal/fgcmFitCycle.py
The base connection's class doesn't actually override any attribute-setting hooks, but if it did, we'd want it to fire.
We also don't need to explicitly update the self.<connection-type> sets anymore, as those are handled by the metaclass.
> DM-44583: Use setattr instead of object.__setattr__.

- tests/config/fgcmCalibrateTractTableHsc.py
- tests/fgcmcalTestBase.py
- tests/test_fgcmcal_hsc.py
The tract fit test seems to be unstable because it is not running to full convergence.  Due to the limited amount of data the fit does not really want to converge in a reasonable amount of time for unit tests.  To improve things (I hope) I have updated the number of iterations to get to better convergence and updated the reference number and increased the tolerance.
> DM-45829: Increase tract fit number of iterations and update reference value.
